### ISSUE TITLE
code blocks are not displayed

### ISSUE THREAD

**Issue by white-gecko** [dokufreaks/plugin-creole#10]
If I create code blocks in '{{{' and '}}}' in a creole page it will not render them in the final output.
For example see: https://github.com/AKSW/Erfurt/wiki/Getting-Started

**Comment by LarsGit223** [comment]
I tested this example code blocks:
```
{{{
//This// does **not** get [[formatted]] 
}}}

{{{//This// does **not** get [[formatted]]}}}
```
Both seem to work fine. Can you please provide an example that does not work?

**Comment by white-gecko** [comment]
Probably this was solved in the meantime, as the result on the example page looks fine.
