### ISSUE TITLE
bold text does not stop on empty line

### ISSUE THREAD

**Issue by LarsGit223** [dokufreaks/plugin-creole#16]
According to Creole 1.0 specs formatted text like bold text does not necessarily need an matching end text. The formatting shall automatically stop on an empty line.

E.g.:
```
Character formatting extends across line breaks: **bold,
this is still bold. This line deliberately does not end in star-star.

Not bold. Character formatting does not cross paragraph boundaries.
```

So the text part **bold, this is still bold. This line deliberately does not end in star-star.** should be bold, the rest not. Currently this example is not displayed as bold text because the expected closing **star star** is missing.

**Comment by LarsGit223** [comment]
The unittest function testing this case is ```test_bold_multiline()```.

**Comment by bmolitor** [comment]
I seem to remember looking into this years ago and coming to the conclusion that it was related to a bug (or feature) in the core renderer, which did (does?) not close formatting between paragraphs: https://bugs.dokuwiki.org/index.php?do=details&task_id=1574

This applies to italic as well.

**Comment by LarsGit223** [comment]
Yes, the core renderer still behaves like that. If you do not enter the closing tag, nothing happens, the formatting is not recognized.

I don't see any description on the syntax page stating that DokuWiki is supporting this behaviour. So for the core renderer itself I would say everything works as designed/as it should.

But for the Creole plugin it would be nice to be as close to the specs as possible.

**Comment by LarsGit223** [comment]
I fixed this in branch **creole10** but I will not merge it right now, so this issue will stay open until I'm sure that I got a stable version.

The change fixes the issue for underline, italic, bold, subscript, superscript and monospace.

**Comment by LarsGit223** [comment]
Forgot to say it's fixed for headers. Meaning a new header closes formatting tags now.

The following things still need to be added to close formatting:
- empty line
- list item
- table cell

**Comment by bmolitor** [comment]
Seems to work for me at first glance -- will keep testing and update if
I run into any issues.

**Comment by LarsGit223** [comment]
An empty line, list item and table now also close/stop formatting. See fad6255d814ad38950c3fe9fe05123f0bbad3b88 in branch ```creole10```.

**Comment by bmolitor** [comment]
Seems to work as intended on my end. Kudos!

**Comment by LarsGit223** [comment]
Thanks for testing!
I will close this issue but still keep everything in branch ```creole10``` for now - there is still work to do.
