### ISSUE TITLE
Question: Editor Toolbar Support in the near future?

### ISSUE THREAD

**Issue by fthommen** [dokufreaks/plugin-creole#18]
[translation of an email unsuccesfully sent to Gina Haeussge and Michael Klier]

Hi,

we are currently evaluating the move from a basically Creole markup based WIki (XWiki) to DokuWiki.  The Creole Plugin has shown to be extremely helpful in this matter as it facilitates content migration by copy-paste.  However, the editor toolbar still creates DW header hierarchies instead of Creole header hierarchies.  Already in 2006 there was a discussion on https://www.dokuwiki.org/plugin:creole, if the plugin should modify the editor toolbar accordingly.  What is the state of this project?  Can we expect this plugin to support the editor toolbar in the near future or should we rather not count on this feature?

Cheers
Frank

**Comment by michitux** [comment]
Apart from @LarsGit223 there is currently nobody working on this plugin as far as I'm aware and I wouldn't consider this plugin to be actively developed (unless @LarsGit223 intends to do this which is something only he can answer). So I wouldn't expect anything. However if you really want/need this feature you could always consider paying somebody to implement this, there is a [list of people offering paid DokuWiki support](https://www.dokuwiki.org/faq:support#professional_support_and_services). We would happily accept a pull request implementing this (if the code quality is acceptable).

**Comment by LarsGit223** [comment]
I confirm what @michitux wrote.

I did changes on it and also might do changes in the future but I'm busy with the ODT plugin for the moment.

**Comment by fthommen** [comment]
In the last days we've implemented a very raw but basically working XWiki Markup converter plugin and thus we will not need the creole-plugin any more.  Thanks anyway for your answers
