### ISSUE TITLE
Linebreak handling according to Creole 1.0

### ISSUE THREAD

**Issue by ddvlad** [dokufreaks/plugin-creole#2]
Creole 1.0 specifies at http://wikicreole.org/wiki/Creole1.0#section-Creole1.0-LineBreaks that line breaks should be rendered as whitespace. This is a change from 0.3, which is the version the plugin was written for. The linked page also recommends that an option be added for treating linebreaks as one way or the other.

**Comment by LarsGit223** [comment]
Done.
Per default whitespace will be inserted now. A new config option also allows to keep linebreaks.
