### ISSUE TITLE
'Doku_Handler_List' not found

### ISSUE THREAD

**Issue by szigetva** [dokufreaks/plugin-creole#26]
My site stopped working after an update (where php-apache was updated).  Downgrading php-apache did not help.  The server log said:
``[php7:error] [pid 1048641] [client xxx] PHP Fatal error:  Uncaught Error: Class 'Doku_Handler_List' not found in /var/lib/dokuwiki/plugins/creole/syntax/listblock.php:89\nStack trace:\n#0 /usr/share/webapps/dokuwiki/inc/load.php(147): require()\n#1 [internal function]: load_autoload('syntax_plugin_c...')\n#2 [internal function]: spl_autoload_call('syntax_plugin_c...')\n#3 /usr/share/webapps/dokuwiki/inc/Extension/PluginController.php(103): class_exists('syntax_plugin_c...', true)\n#4 /usr/share/webapps/dokuwiki/inc/pluginutils.php(54): dokuwiki\\Extension\\PluginController->load('syntax', 'creole_listbloc...', false, false)\n#5 /usr/share/webapps/dokuwiki/inc/parserutils.php(559): plugin_load('syntax', 'creole_listbloc...')\n#6 /usr/share/webapps/dokuwiki/inc/parserutils.php(204): p_get_parsermodes()\n#7 /usr/share/webapps/dokuwiki/inc/parserutils.php(181): p_get_instructions('======Jegyz\\xC5\\x91k\\xC3...')\n#8 /usr/share/webapps/dokuwiki/inc/parserutils.php(501): p_cached_instructions('/usr/share/weba...', false, 'about:minutes:2...')\n#9 /usr/share/webapps/dokuwiki/inc/parserut in /var/lib/dokuwiki/plugins/creole/syntax/listblock.php on line 89``
After `chmod 000 /var/lib/dokuwiki/plugins/creole` the site works, but I would love to get creole back.  Any hints?

edit:
creole had to be manually updated, sorry for the noise

**Comment by Klap-in** [comment]
Since the updates #24 and #25, this issue should be solved. So you could use the plugin again if you update it.
