### ISSUE TITLE
version 2020-08-21 no longer support Greebo?

### ISSUE THREAD

**Issue by gilcot** [dokufreaks/plugin-creole#28]
I've updated to 2020-08-21 and my DokuWiki became unusable (blank page…) I had to remove the plugin manually on the server (as even the admin area couldn't be reached) in order to have the site working back. Later, I tried a fresh install (i.e. `doku.php?id=start&do=admin&page=extension&tab=search&q=` link) with the same result (blank page, hence some PHP fatal inside)

**Comment by Klap-in** [comment]
The release of the creole plugin, that adds support for the Hogfather release, is not backward compatible. For older DokuWiki versions you have to use an older version of the creole plugin.

**Comment by Klap-in** [comment]
@lpaulsen93 could you maybe add a realease/tag for the last version of the creole plugin before the not-backward compatibel changes? I do not yet see how to create a release.

**Comment by lpaulsen93** [comment]
@Klap-in There has been a change since 2020-08-21 so I upped the version and created a release from there. I updated the plugin page accordingly and added a compatibility note under _"Installation"_. Feel free to add changes/improvements.
